/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilitaRouteImport } from './routes/accessibilita'
import { Route as CondividiRouteImport } from './routes/condividi'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as TagTagRouteImport } from './routes/tag.$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilitaRoute = AccessibilitaRouteImport.update({
  id: '/accessibilita',
  path: '/accessibilita',
  getParentRoute: () => rootRouteImport,
} as any)
const CondividiRoute = CondividiRouteImport.update({
  id: '/condividi',
  path: '/condividi',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibilita': typeof AccessibilitaRoute
  '/condividi': typeof CondividiRoute
  '/cookie': typeof CookieRoute
  '/privacy': typeof PrivacyRoute
  '/termini': typeof TerminiRoute
  '/tag/$tag': typeof TagTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibilita': typeof AccessibilitaRoute
  '/condividi': typeof CondividiRoute
  '/cookie': typeof CookieRoute
  '/privacy': typeof PrivacyRoute
  '/termini': typeof TerminiRoute
  '/tag/$tag': typeof TagTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibilita': typeof AccessibilitaRoute
  '/condividi': typeof CondividiRoute
  '/cookie': typeof CookieRoute
  '/privacy': typeof PrivacyRoute
  '/termini': typeof TerminiRoute
  '/tag/$tag': typeof TagTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibilita'
    | '/condividi'
    | '/cookie'
    | '/privacy'
    | '/termini'
    | '/tag/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibilita'
    | '/condividi'
    | '/cookie'
    | '/privacy'
    | '/termini'
    | '/tag/$tag'
  id:
    | '__root__'
    | '/'
    | '/accessibilita'
    | '/condividi'
    | '/cookie'
    | '/privacy'
    | '/termini'
    | '/tag/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilitaRoute: typeof AccessibilitaRoute
  CondividiRoute: typeof CondividiRoute
  CookieRoute: typeof CookieRoute
  PrivacyRoute: typeof PrivacyRoute
  TerminiRoute: typeof TerminiRoute
  TagTagRoute: typeof TagTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibilita': {
      id: '/accessibilita'
      path: '/accessibilita'
      fullPath: '/accessibilita'
      preLoaderRoute: typeof AccessibilitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condividi': {
      id: '/condividi'
      path: '/condividi'
      fullPath: '/condividi'
      preLoaderRoute: typeof CondividiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilitaRoute: AccessibilitaRoute,
  CondividiRoute: CondividiRoute,
  CookieRoute: CookieRoute,
  PrivacyRoute: PrivacyRoute,
  TerminiRoute: TerminiRoute,
  TagTagRoute: TagTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
